import { faker } from '@faker-js/faker';
export const testConfig = {
    url:'https://hrmsdev1.azurewebsites.net/',
    validusername: `dotnetemployee@intonenetworks.com`,
    InValidusername: 'dotemployee@intonenetworks.com',
    Validpassword: `Password1!`,
    InValidpassword:`Password`,
    waitForElement: 120000,
    Department: 'Technical Support (Hyderabad)',
    Severity: 'High',
    TicketType: 'Internet',
    TicketSummary: 'The Ticket summary',
    Ticketstate:'Open',
    Status: 'Resolved',
    TicketRemarks: 'The Ticket Resolved',
    updateAssertion: 'Ticket submitted successful.Please check the mail',
    Invalidmessage: 'Invalid UserName or Password...!',
    techsupporthodusername: 'techsupporthod@intonenetworks.com',
    techsupporthodpassword:'Password1!',
    selectapproval:'Dot Net Hod',
    toastmessage :'Ticket Submitted Successfully. Please Check The Mail',
    techsupportempusername: `techsupportemp@intonenetworks.com`,
    password: `Password1!`,
    techsupportpassword:`Password1!`,
    subcategory:faker.name.firstName(),
    Item:faker.name.firstName(),
    Categoryname:faker.name.firstName(),
    Categorycode:faker.random.numeric(3),
    Subcategorycode:faker.random.numeric(3),
    Specification1:faker.name.firstName(),
    Specification2:faker.name.firstName(),
    serial:faker.name.firstName(),
    updatedtoastmessage:'Data has been Successfully Updated.',
    Assettoastmessage:'Asset has been created Successfully.',
    logouttoastmessage:'Logout Success..',
    approvaltoastmessage:'Successfully Approved',

}